### ISSUE TITLE
Setup instructions in conjunction with jaeger-client-python leads to pitfall

### ISSUE THREAD

**Issue by bitglue** [opentracing-contrib/python-django#7]
See https://github.com/uber/jaeger-client-python/issues/60. Doing the obvious setup, according to the readme of these two projects, leads to a deadlock which is quite tricky to sort out.

I've not yet found an elegant workaround, though I'm not an expert in Jaeger, or Django. In the linked issue, it's suggested the Jaeger tracer not be initialized until after the WSGI server (gunicorn in my case) forks. That seems like a good idea, even if it didn't deadlock.

The closest solution would seem to be putting the initialization of the Jaeger tracer in gunicorns `post_fork()` hook (or similar for other WSGI servers). Trouble is by that time I'd think `OpenTracingMiddleware` [has already saved a reference to the tracer](https://github.com/opentracing-contrib/python-django/blob/9b33c75d55150feb6e4a945e1f28c0ff1f7550c6/django_opentracing/middleware.py#L21-L24). So I'm looking at doing something ugly.

**Comment by dudymas** [comment]
So it looks like someone made a fix for this already in #6 , which is from work on the issue at jaegertracing/jaeger-client-python#69
The PR appears to not be approved because the code has jaeger_client hardcoded in and also the maintainer hasn't been given a clear enough picture as to why this solution has to be in place.

**Comment by dudymas** [comment]
I'm hoping @tanner-bruce , @bhs ,  or @carlosalberto  could comment, as we could use this fix too.

**Comment by tanner-bruce** [comment]
@dudymas I'm hoping to get back to it really soon, simply haven't had a chance. There are a few things that need to be fixed in the PR, as well as a change or two and I need to rationalize some of the decisions. I also want to test a different approach to storing the root span that would make the middleware arguably cleaner.

**Comment by dudymas** [comment]
@tanner-bruce would you mind if I make a PR to your repo? I already removed the jaeger client dep and also dried up the middleware to use more of the django helper class for init

**Comment by tanner-bruce** [comment]
@dudymas sure, thanks for putting in the work.

**Comment by ror6ax** [comment]
Hi guys, thanks for your work on this! Any idea when can we expect this in master? If there's any work that still needs to be done, I'd be happy to do that...

**Comment by mikebryant** [comment]
@ror6ax I've tried a different way of approaching this in #9

**Comment by ror6ax** [comment]
@mikebryant - awesome! Hopefully this gets merged soon...
